### ISSUE TITLE
How should I estimate costs for using this setup as a backend?

### ISSUE THREAD

**Issue by bikegriffith** [awslabs/aws-mobile-react-native-starter#1]
Do you have a calculator or formula for all the services combined, i.e. based on X bytes in S3, Y lambda requests, ...?  Would be very useful to understand the cost at the current rates.

**Comment by miguel550** [comment]
I was thinking the same thing, if there is a way of calculating this combination of services without actually buying the services would be useful.

**Comment by talkingtab** [comment]
And what is the best practice to limit your cost. If I'm playing around with this thing that is so complex how do I ensure that I do not accidentally owe Amazon $10,000?  I've read that AWS Is generous about mistake, and I would love to try it out - but I can't find a deterministic way to limit my financial exposure.

**Comment by alexkuc** [comment]
There is a way to set up billing alerts. For example, once a service exceeds certain billing threshold (e.g. $50) you will be automatically notified. ([Monitoring Your Usage and Costs](http://docs.aws.amazon.com/awsaccountbilling/latest/aboutv2/monitoring-costs.html))

**Comment by brianfoody** [comment]
Costs will be basically non-existent unless you run serious load but best to set up a billing alert anyway.

**Comment by RTHRELKELD1980** [comment]
Hi, pricing information including free tier data can be found here: https://aws.amazon.com/mobile/pricing/

AWS also has a calculator for performing estimates: https://calculator.s3.amazonaws.com/index.html

As others have mentioned as well it's a good idea to setup billing alerts: http://docs.aws.amazon.com/awsaccountbilling/latest/aboutv2/free-tier-alarms.html
