### ISSUE TITLE
Need a "Resend Validation"

### ISSUE THREAD

**Issue by WChoy** [awslabs/aws-mobile-react-native-starter#11]
Should include a "Resend Validation" button in the example, if you have email/phone confirmation. 
 
If the user does not receive the confirmation code, the first time.  There is no way to resend the code for validation.

**Comment by WChoy** [comment]
Or have the "Forgot password" sent a confirmation notification if the user has not validated information.

**Comment by manueliglesias** [comment]
Hi @WChoy ,

Thank you for trying this starter! I agree with you, the use cases you describe are valid and needed on a typical app.

For now, this starter shows only a small but still functional sub-set of use cases, the scenario you describe is currently not covered by this sample/starter app. 

For now, if you need this functionality in your own app, what I can suggest is that you take a look at the [aws-amplify](https://github.com/aws/aws-amplify) library, it has support for ["Resend validation"](https://github.com/aws/aws-amplify/blob/9c135713e2e97cd40665dd19122952c69a1754d0/packages/aws-amplify-react-native/dist/components/auth/ConfirmSignUp.js#L60)

And of course, please feel free to submit a PR to this repo with the functionality if you ever feel like doing so :)
