### ISSUE TITLE
":CFBundleIdentifier", Does Not Exist

### ISSUE THREAD

**Issue by engrdroid704** [awslabs/aws-mobile-react-native-starter#12]
I am not using npm 4. I am using the latest version of yarn (yarn run v1.2.0). This is after I ran the command "yarn run ios". I have attached a screen shot:

<img width="643" alt="screen shot 2017-10-12 at 1 15 49 pm" src="https://user-images.githubusercontent.com/23033323/31479033-97998a20-af4f-11e7-9e76-80a8ad02a4eb.png">

**Comment by RTHRELKELD1980** [comment]
This might be a React Native issue potentially related to either your host OS, version of XCode or Node: https://github.com/facebook/react-native/issues?utf8=✓&q=CFBundleIdentifier%20

Have you tried using Android? Are you using the latest version of XCode?
