### ISSUE TITLE
Why not import aws-sdk/dist/aws-sdk-react-native

### ISSUE THREAD

**Issue by canhnht** [awslabs/aws-mobile-react-native-starter#15]
I see the code only imports `aws-sdk`. Why don't we use `aws-sdk/dist/aws-sdk-react-native` as mentioned [here](https://github.com/aws/aws-sdk-js#in-react-native)?

**Comment by manueliglesias** [comment]
Hi @canhnht 

Thanks for trying the starter!

The reason for doing it is because of aws/aws-sdk-js#1618

Closing the issue
