### ISSUE TITLE
in src/Components/SignUp StackNavigator with only one screen. What for?

### ISSUE THREAD

**Issue by waubau** [awslabs/aws-mobile-react-native-starter#16]
Can you please clarify the point behind this code:
``` 
const SignUpStack = StackNavigator({
  SignUp: {
    screen: props => <SignUp {...props} onSignUp={props.screenProps.onSignUp} />,
    navigationOptions: {
      title: Constants.APP_NAME,
    }
  },
```
If you have only one screen you can just pass the component SignUp right into the parent Navigator with the same resulting behaviour or am I missing something?

**Comment by cosmosof** [comment]
Login stack houses Login and Forgot password. You don't want your Signup screen next to forgot password.
