### ISSUE TITLE
can't find variable Buffer

### ISSUE THREAD

**Issue by notlose** [awslabs/aws-mobile-react-native-starter#19]
having problem while integrating with existing app,
added lib from sample project, 
imported aws-exports file,
updated export class with WithApi and WithAuth
and getting can't find variable Buffer error while trying to call lambda api

try {
      api.restRequest(requestParams).then((data)=>{
        console.warn(data);
      });

    } catch (err) {
      console.warn(err);
    }

should be caused by node_modules/aws4-react-native/aws4.js line 119 
Buffer.byteLength(request.body)

anyone experienced the same problem?
i am using react native 0.49.3

**Comment by RTHRELKELD1980** [comment]
Can you add the following code to your app at it's entry point (see client/App.js for example):

`global.Buffer = global.Buffer || require('buffer').Buffer;`
