### ISSUE TITLE
Dependency graph error

### ISSUE THREAD

**Issue by watrick** [awslabs/aws-mobile-react-native-starter#2]
When executing 'npm run ios' I come across this error below after it starts running the packager on a local port 

`Error watching file for changes: EMFILE`
`{"code":"EMFILE","errno":"EMFILE","syscall":"Error watching file for changes:","filename":null}
Error: Error watching file for changes: EMFILE
    at exports._errnoException (util.js:1020:11)
    at FSEvent.FSWatcher._handle.onchange (fs.js:1420:11)
`

It then crashes the iPhone simulator on my MacBook 

![image](https://user-images.githubusercontent.com/2829918/30618959-ac220888-9d51-11e7-9c7c-636d2bd6c55c.png)

How can I fix these issues?

**Comment by manueliglesias** [comment]
Hi @watrick, I am glad you found a solution. If you are still experiencing errors, please let us know by opening a new issue.
