### ISSUE TITLE
`npm run ios` fails with "Print: Entry, ":CFBundleIdentifier", Does Not Exist"

### ISSUE THREAD

**Issue by RaghuMurugesan** [awslabs/aws-mobile-react-native-starter#20]
`npm run ios` fails

When I run `npm run ios` I am encountering the bellow err, I am using `npm@5.4.2 and node@v8.8.1`

>Command /bin/sh failed with exit code 2
>
>
>
>** BUILD FAILED **
>
>
>The following build commands failed:
>
>	PhaseScriptExecution Start\ Packager /Users/foo/ws/foocode/serverless/aws-mobile-react-native-starter/client/ios/build/Build/Intermediates.noindex/React.build/Debug-iphonesimulator/React.build/Script-006B79A01A781F38006873D1.sh
>(1 failure)
>
>Installing build/Build/Products/Debug-iphonesimulator/awsmobilereactnativesample.app
>An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
>Failed to install the requested application
>An application bundle was not found at the provided path.
>Provide a valid path to the desired application bundle.
>Print: Entry, ":CFBundleIdentifier", Does Not Exist
>
>Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/awsmobilereactnativesample.app/Info.plist
>Print: Entry, ":CFBundleIdentifier", Does Not Exist
>
>
>npm ERR! code ELIFECYCLE
>npm ERR! errno 1
>npm ERR! aws-mobile-react-native-sample@0.1.0 ios: `react-native run-ios`
>npm ERR! Exit status 1
>npm ERR!
>npm ERR! Failed at the aws-mobile-react-native-sample@0.1.0 ios script.
>npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
>
>npm ERR! A complete log of this run can be found in:
>npm ERR!     /Users/ragmurug/.npm/_logs/2017-10-30T15_00_16_168Z-debug.log

**Comment by RTHRELKELD1980** [comment]
Can you see if the recommendations in [this issue](https://github.com/awslabs/aws-mobile-react-native-starter/issues/12) help?

**Comment by udugam** [comment]
I had this error at first and got the :CFBundleIdentifier", Does Not Exist" #20 error to disappear once I downgraded to npm version 4.6.1.

I'm still getting the last few errors though (see my post named " Failed at the aws-mobile-react-native-sample@0.1.0 ios script."

**Comment by udugam** [comment]
Just solved the outstanding errors I had but Updating Xcode.
