### ISSUE TITLE
`npm run ios` fails with "RCTFatal" "__28-[RCTCxxBridge handleError:]_block_invoke"

### ISSUE THREAD

**Issue by muygrafico** [awslabs/aws-mobile-react-native-starter#21]
npm run ios builds app, but show error from start (red page).

When I run npm run ios I am encountering the bellow err, I am using npm@5.4.2 and node@v8.8.1

TransformError: /Users/gh/Projects/current/aws-mobile-react-native-starter/client/index.ios.js: Couldn't find preset "react" relative to directory "/Users/gh/Projects/current"

RCTFatal
__28-[RCTCxxBridge handleError:]_block_invoke
_dispatch_call_block_and_release
_dispatch_client_callout
_dispatch_main_queue_callback_4CF
__CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
__CFRunLoopRun
CFRunLoopRunSpecific
GSEventRunModal
UIApplicationMain
main
start

on terminal:

error: bundling failed: "TransformError: /Users/gh/Projects/current/aws-mobile-react-native-starter/client/index.ios.js: Couldn't find preset \"react\" relative to directory \"/Users/gh/Projects/current\""

**Comment by mrlazy1324** [comment]
Did you find the solution for this?
I do all type of solution but still error present.
Not working ahead. I am stuck there.

**Comment by muygrafico** [comment]
I did a monkey patch for component [react-native-promp](https://github.com/jaysoo/react-native-prompt)  (node_modules/react-native-promp) described [here](https://github.com/jaysoo/react-native-prompt/issues/27), also updating [MFAPrompt.js](https://github.com/awslabs/aws-mobile-react-native-starter/blob/master/client/src/Components/MFAPrompt.js)
component with properly import of PropTypes. 

Instead of this on line 13:
`import React, { PropTypes } from 'react';`
should be:
`import React from 'react';`
`import { PropTypes } from 'prop-types';`

Downside of it, get's broken on each npm install, so keep that in mind, 'react-native-promp' need to be fixed from source. Let me know if it works,

Cheers.

**Comment by mrlazy1324** [comment]
Still error present.

**Comment by mrlazy1324** [comment]
Hey I solved this by checking localhost is available or not.
steps:

1) Check localhost running or not by ping. Enter this command in terminal.
 ping -c 4 localhost

2) If a ping is not received then check hosts file by this terminal command.
cat /etc/hosts

3) If there are blank sheets. Then open editor via this command.
sudo vi  /etc/hosts

for insert press **i**

Add Copy this text
**##
# Host Database
#
# localhost is used to configure the loopback interface
# when the system is booting.  Do not change this entry.
##
127.0.0.1	localhost
255.255.255.255 broadcasthost
::1             localhost**

After for save and quit command : **wq**

Now run your project enjoy.

Cheers.
