### ISSUE TITLE
'npm run android' fails with error:  Failed at the aws-mobile-react-native-sample@0.1.0 android script.

### ISSUE THREAD

**Issue by KowalskiTom** [awslabs/aws-mobile-react-native-starter#22]
Here is the output from the debug file: 

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'android' ]
2 info using npm@5.4.2
3 info using node@v8.8.1
4 verbose run-script [ 'preandroid', 'android', 'postandroid' ]
5 info lifecycle aws-mobile-react-native-sample@0.1.0~preandroid: aws-mobile-react-native-sample@0.1.0
6 info lifecycle aws-mobile-react-native-sample@0.1.0~android: aws-mobile-react-native-sample@0.1.0
7 verbose lifecycle aws-mobile-react-native-sample@0.1.0~android: unsafe-perm in lifecycle true
8 verbose lifecycle aws-mobile-react-native-sample@0.1.0~android: PATH: #######
9 verbose lifecycle aws-mobile-react-native-sample@0.1.0~android: CWD: C:\github\aws-mobile-react-native-starter\client
10 silly lifecycle aws-mobile-react-native-sample@0.1.0~android: Args: [ '/d /s /c', 'react-native run-android' ]
11 silly lifecycle aws-mobile-react-native-sample@0.1.0~android: Returned: code: 1  signal: null
12 info lifecycle aws-mobile-react-native-sample@0.1.0~android: Failed to exec android script
13 verbose stack Error: aws-mobile-react-native-sample@0.1.0 android: `react-native run-android`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:280:16)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at EventEmitter.emit (events.js:213:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at ChildProcess.emit (events.js:213:7)
13 verbose stack     at maybeClose (internal/child_process.js:927:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
14 verbose pkgid aws-mobile-react-native-sample@0.1.0
15 verbose cwd C:\github\aws-mobile-react-native-starter\client
16 verbose Windows_NT 10.0.16299
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "android"
18 verbose node v8.8.1
19 verbose npm  v5.4.2
20 error code ELIFECYCLE
21 error errno 1
22 error aws-mobile-react-native-sample@0.1.0 android: `react-native run-android`
22 error Exit status 1
23 error Failed at the aws-mobile-react-native-sample@0.1.0 android script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by bdelville** [comment]
Downgrade to npm 4 seems to work to most people. 
But for me even with it I have the same issue

**Comment by aalkz** [comment]
Had the same problem, using `react-native run-android`  instead of `npm run android` worked for me. I had to add `Android/Sdk/platform-tools` to my PATH for it to run `adb` correctly too.

**Comment by manueliglesias** [comment]
Hi @KowalskiTom ,

Can you verify if @aalkz 's solution works for you? Feel free to reopen this issue if needed.
