### ISSUE TITLE
Error: undefined is not an object (evaluating '_react2.PropTypes.string')

### ISSUE THREAD

**Issue by Dimitrios6** [awslabs/aws-mobile-react-native-starter#23]
When I try to integrate features into my React Native app, following instructions on section "Use features in your app." Error: undefined is not an object (evaluating '_react2.PropTypes.string')

Steps to reproduce the bug:
"create-react-native-app newapp --> 
cd newapp --> 
npm run eject # Eject as "React Native" --> 
set home screen/Android Studio and Xcode projects: newapp --> 
Downloaded the aws-exports.js (file that work fine with the repository cloned project) and I placed it in the root of newapp --> 
Copied lib folder from the repository cloned project (starter app) --> 
npm install --> 
npm install aws-sdk react-native-aws-cognito-js react-native-prompt --save --> 
react-native link --> 
then in the App.js import '{ WithAuth } from './lib/Categories/Auth/Components';' --> 
import '{ StyleSheet, Text, View, Button } from 'react-native';' --> 
till now the newapp load fine but when I add -->
'import { SignIn, SignUp } from './lib/Categories/Auth/Components/Examples';
this is the result:

![screenshot_1509739696](https://user-images.githubusercontent.com/16239043/32396052-125be460-c0e4-11e7-9a6e-791aaa200091.png)

I suggest to update the set of libraries (under client/lib) and the MFAPrompt.js. to help us integrate features into our React Native app

My Environment

software	version
react: 16.0.0-beta.5,
react-native: 0.49.5,
npm: 5.5.1

**Comment by bohui** [comment]
I use this tool to do code migration, this may help:
jscodeshift -t react-codemod/transforms/React-PropTypes-to-prop-types.js [your_src_path]

Refer to: https://reactjs.org/blog/2017/04/07/react-v15.5.0.html#migrating-from-react.proptypes

**Comment by Dimitrios6** [comment]
Thanks, but which is the correct [src_path]?

I add the root directory of the app as 'src_path' but the result is:
ERROR Transform file /Users/Desktop/newapp/react-codemod/transforms/React-PropTypes-to-prop-types.js does not exist

**Comment by bohui** [comment]
It seems you haven't install react-codemod yet.

1. yarn global add jscodeshift
2. git clone https://github.com/reactjs/react-codemod.git or download a zip file from https://github.com/reactjs/react-codemod/archive/master.zip
3. Run yarn install in the react-codemod directory
4. jscodeshift -t <codemod-script> <path>
* use the -d option for a dry-run and use -p to print the output for comparison;
* if you use flowtype, you might also need to use --parser=flow.

Refer to https://github.com/reactjs/react-codemod#react-proptypes-to-prop-types

**Comment by Dimitrios6** [comment]
Thanks, Fixed!

1. yarn global add jscodeshift
2. git clone https://github.com/reactjs/react-codemod.git or download a zip file from https://github.com/reactjs/react-codemod/archive/master.zip (in the newapp directory)
3. Run yarn install in the react-codemod directory
4. npm install --save prop-types (in the newapp directory)
jscodeshift -t react-codemod/transforms/React-PropTypes-to-prop-types.js /Users/Desktop/newapp
