### ISSUE TITLE
error(s) after eject —at Sign in Sign out

### ISSUE THREAD

**Issue by flowpayManfred** [awslabs/aws-mobile-react-native-starter#24]
So this project works as expect until ejecting. Android still works from command line, but cannot _npm run IOS_ from command line, because of this error:

> Manfreds-MacBook-Pro:mvp manfredneustifter$ npm run ios

> mvp@0.1.0 ios /Users/manfredneustifter/mvp
> react-native run-ios

Scanning folders for symlinks in /Users/manfredneustifter/mvp/node_modules (34ms)
Found Xcode project mvp.xcodeproj
xcodebuild: error: SDK "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.0.sdk" cannot be located.
xcrun: error: unable to find utility "instruments", not a developer tool or in PATH

Command failed: xcrun instruments -s
xcodebuild: error: SDK "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.0.sdk" cannot be located.
xcrun: error: unable to find utility "instruments", not a developer tool or in PATH

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mvp@0.1.0 ios: `react-native run-ios`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mvp@0.1.0 ios script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/manfredneustifter/.npm/_logs/2017-11-04T04_42_49_406Z-debug.log
Manfreds-MacBook-Pro:mvp manfredneustifter$ 

> 
**-->** But if I open the project in Xcode, it does build successfully, and can run on emulator in Xcode.

However, after the next steps: Sign in Sign out, neither android nor ios work. 
https://github.com/awslabs/aws-mobile-react-native-starter#sign-up-and-sign-in-

On android, the build seems to work, but when opening the app in the android emulator I get this:
![screen shot 2017-11-04 at 2 57 38 pm](https://user-images.githubusercontent.com/32832250/32402484-b9b2bacc-c170-11e7-8788-f43fe4adb64b.png)

and on IOS this:
![screen shot 2017-11-04 at 2 37 50 pm](https://user-images.githubusercontent.com/32832250/32402371-e0c47ec8-c16d-11e7-8c81-271ea32370bb.png)

App.js
`import React from 'react';
import { StyleSheet, Text, View, Button} from 'react-native';
import { WithAuth } from './lib/Categories/Auth/Components';
import { SignIn, SignUp } from './lib/Categories/Auth/Components/Examples';

export default WithAuth(class App extends React.Component {
  render() {
    const { session } = this.props;

    return (
      session ?
        (<View style={styles.container}>
          <Button title="Sign Out" onPress={() => this.props.doSignOut()} />
        </View>)
        :
        (<View style={styles.container}>
          <SignIn {...this.props} />
          <SignUp {...this.props} />
        </View>)
    );
  }
});

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});`

**Comment by flowpayManfred** [comment]
and, is there any way to make this project work with Expo? I dont want to eject

**Comment by 7772** [comment]
You can resolve PropType Error by implementing [react-codemod](https://github.com/reactjs/react-codemod).

You should this process.

1. $ yarn global add jscodeshift
2. In your app directory..
    $ git clone https://github.com/reactjs/react-codemod.git
3. In ../your-app-directory/react-codemod
    $ yarn install
4. In your app directory..
    Here, <path> is your app directory root.
    $ jscodeshift -t react-codemod/transforms/React-PropTypes-to-prop-types.js <path>

**Comment by nidsharm** [comment]
Hey, 

We have updated our dependency on prop-type in #39. Can you please retry it? Feel free to open the issue again if there are still some problems with it.
Thanks.
