### ISSUE TITLE
"Invalid Phone Number Format"

### ISSUE THREAD

**Issue by udugam** [awslabs/aws-mobile-react-native-starter#27]
Is there a specific format for the phone number part of the user sign up? I'm following the "Sign-up and Sign-In example and am getting this message in the app when I try and register.

**Comment by devin42r** [comment]
I found that it required '+1' in front for North America

**Comment by undefobj** [comment]
@devin42r answer is correct, country code is necessary. More information can be found here: http://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-settings-attributes.html
