### ISSUE TITLE
Blank Upload Photo page

### ISSUE THREAD

**Issue by devin42r** [awslabs/aws-mobile-react-native-starter#28]
![image](https://user-images.githubusercontent.com/9112811/32983988-cc135074-cc5a-11e7-97f9-67ddc15eb775.png)

My upload photo page is rendering nothing...

**Comment by nidsharm** [comment]
Hey devin42r, 

You probably don't have media on your device. Use the simulator camera to take a few screenshots, and then the upload screen will have all your screenshots.

**Comment by nidsharm** [comment]
I'm closing the issue for now. Please feel free to reopen it if you still face this problem.

Thanks.
