### ISSUE TITLE
Cognito performance

### ISSUE THREAD

**Issue by alexkuc** [awslabs/aws-mobile-react-native-starter#3]
In the past, I recall that some people complained that JS version of Cognito on mobile clients (i.e. mobile apps produced via JS framework) was too slow unless a native bridge was used. Does this setup address performance issue?

For example, this fork of Cognito JS ([AirLabsTeam/react-native-aws-cognito-js](https://github.com/AirLabsTeam/react-native-aws-cognito-js))
`This project uses Native Modules to handle intensive math operations on the device using the React Native bridge.`

**Comment by manueliglesias** [comment]
Hi @alexkuc,

This starter app addresses those concerns using the fork you just pointed out.

While I don't have an ETA, work is being done to officially support RN.

**Comment by jmparsons** [comment]
@alexkuc Until there is an officially supported library I will keep the one I wrote up to date with the current https://github.com/aws/amazon-cognito-identity-js/.
