### ISSUE TITLE
"Next" button spins forever in "Set up your starter kit" step during deployment

### ISSUE THREAD

**Issue by mutazmq** [awslabs/aws-mobile-react-native-starter#30]
Please see the attachment. "Next" button has been spinning for the last hour. How can I handle this issue? Thanks

<img width="1680" alt="screen shot 2017-12-04 at 10 43 57 am" src="https://user-images.githubusercontent.com/34026/33539777-6f3e063a-d8e1-11e7-8b13-3912436a6725.png">

**Comment by nidsharm** [comment]
Hey mutazmq, 

You might have run out of S3 buckets to see this issue. Can you please check that you have more capacity for MobileHub to create buckets(we create 3 buckets for this project) in your account? 

Thanks.

**Comment by nidsharm** [comment]
Hey mutazmq,

We haven't heard back from you on the issue. I'm closing the issue, please feel free to re-open it if you continue to face the problem.

Thanks,
Nidhi
