### ISSUE TITLE
Various components are not checked out from repo but are described in README.

### ISSUE THREAD

**Issue by cdupiton** [awslabs/aws-mobile-react-native-starter#35]
Several HOC Components are missing; they are used in the tutorial but are not provided via the repository, so it is impossible to set this starter project up. So far I've seen WithStorage & WithApi missing.

**Comment by nidsharm** [comment]
Hey @cdupiton , 

Thanks for bringing it to our attention. The instructions in the README have been updated. 
The Starter Project initially had helper code and HOCs, but as we released [AWS Amplify](https://github.com/aws/aws-amplify), we replaced these HOCs with simple API calls from the library.

The documentation is now updated with instructions on using these APIs for a new app. I'm closing this issue, please feel free to reopen it if something seems amiss to you. 

Regards,
Nidhi
