### ISSUE TITLE
Problems sign-in and new users

### ISSUE THREAD

**Issue by typemismatch** [awslabs/aws-mobile-react-native-starter#36]
There is something wrong with the app and the signup and sign-in. You end up in an "enter code" loop with Cognito, sometimes you get logged in sometimes you don't. If you create the user first in Cognito you'll never get the confirmation code either so that doesn't work. I do keep getting the code via SMS but it just asks again and send another code.

**Comment by twoolf** [comment]
If your build is like mine, it's not needing a full recycle with another confirmation code -- there does seem to be a bug, but it only needs a delete of one number in the code, then retyping that one digit back again and it will accept it the second time --

**Comment by manueliglesias** [comment]
@typemismatch  This starter has included some changes in #39  to address this.

Please try with the latest versions of both the starter and the aws-amplify-react-native packages and let us know how it goes.

**Comment by typemismatch** [comment]
thanks will do
