### ISSUE TITLE
Builds but  "Unable to load script from assets index.android.bundle"

### ISSUE THREAD

**Issue by kirkins** [awslabs/aws-mobile-react-native-starter#44]
Went through the README and did all the steps. After installing all the dependencies I have the react-native compiling to android with `npm run android`.

I get back "Unable to load script from assets index.android.bundle".

![screenshot_20180114-101216](https://user-images.githubusercontent.com/9503662/34917400-b5e4928c-f913-11e7-97a6-3152682cb63b.png)

Anyone know how I can go about debugging?

**Comment by kirkins** [comment]
Fixed, did 2 changes before finding it worked. I think it was the first one.

1. Top answer on this Q/A, but replace index.js with App.js https://stackoverflow.com/questions/44446523/unable-to-load-script-from-assets-index-android-bundle-on-windows

2. Add folder with `adb` to path had tools but not platform-tools `.bashrc`:

`export PATH=$PATH:$ANDROID_HOME/platform-tools`

**Comment by SourceCipher** [comment]
Had the same issue, to solve this is a nonsense..Found it a nightmare to run react native on android. Issues on every single build.
