### ISSUE TITLE
Running Backend code on local machine during development

### ISSUE THREAD

**Issue by kamipatel** [awslabs/aws-mobile-react-native-starter#48]
Looks like back-end code needs to be deployed to AWS before getting called from client. 
During development is there a way to run backend code locally along with front-end? That will be huge development productivity gain.

**Comment by nidsharm** [comment]
Hi @kamipatel,

It is on our roadmap to integrate local development for serverless apps with AWS Mobile CLI. There is a tool available for the same : https://github.com/awslabs/aws-sam-local , you should be able to use this as of now for local development.

**Comment by kamipatel** [comment]
I tried SAM local. But not able to call localhost from React webapp:-(
