### ISSUE TITLE
Update to support version 0.2 of aws-amplify-react-native

### ISSUE THREAD

**Issue by SteveHoggNZ** [awslabs/aws-mobile-react-native-starter#50]
Version 0.2 of aws-amplify-react-native supports caching login details on the device (amongst other improvements https://github.com/aws/aws-amplify/pull/200)

It would be a great upgrade to this starter if the new library version was supported. Thanks!

**Comment by mlabieniec** [comment]
@SteveHoggNZ PR #49 is already in review hoping to get that merged right away after a but more testing / review.
