### ISSUE TITLE
awsmobile start my-project react-native not working

### ISSUE THREAD

**Issue by smustaoglu** [awslabs/aws-mobile-react-native-starter#57]
there is a missing configuration details.

>awsmobile start my-project react-native

Creating project my-project
Failed to download starter awslabs/aws-mobile-react-native-starter
error: 'git clone' failed with status 128

git is working as standalone.

>git clone https://github.com/awslabs/aws-mobile-react-native-starter
Cloning into 'aws-mobile-react-native-starter'...
remote: Counting objects: 465, done.
remote: Compressing objects: 100% (37/37), done.
Receiving objects:  54% (252/465), 11.13 MiB | 2.75 MiB/s

**Comment by Rick49** [comment]
Having the same problem - git version 2.14.3 on MacOS:

Creating project xxx
⠼ downloading starter awslabs/aws-mobile-react-native-starter ...The authenticity of host 'github.com (192.30.253.112)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
⠼ downloading starter awslabs/aws-mobile-react-native-starter ...
Failed to download starter awslabs/aws-mobile-react-native-starter
error: 'git clone' failed with status 128

**Comment by UnleashedMind** [comment]
Please get the latest version and try again v1.0.15.

**Comment by smustaoglu** [comment]
thanks it is working with v1.0.15.
