### ISSUE TITLE
npm run android not working

### ISSUE THREAD

**Issue by smustaoglu** [awslabs/aws-mobile-react-native-starter#59]
npm run android not working, but >react-native run-android working.

>npm run android

> aws-mobile-react-native-sample@0.1.0 android xxxxxx
> react-native run-android

Looks like you installed react-native globally, maybe you meant react-native-cli?
To fix the issue, run:
npm uninstall -g react-native
npm install -g react-native-cli

npm ERR! Windows_NT 10.0.16299
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "android"
npm ERR! node v7.10.1
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! aws-mobile-react-native-sample@0.1.0 android: `react-native run-android`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the aws-mobile-react-native-sample@0.1.0 android script 'react-native run-android'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the aws-mobile-react-native-sample package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     react-native run-android
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs aws-mobile-react-native-sample
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls aws-mobile-react-native-sample
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     \AppData\Roaming\npm-cache\_logs\2018-02-17T18_58_42_127Z-debug.log

2 info using npm@4.2.0
3 info using node@v7.10.1
4 verbose run-script [ 'preandroid', 'android', 'postandroid' ]
5 info lifecycle aws-mobile-react-native-sample@0.1.0~preandroid: aws-mobile-react-native-sample@0.1.0
6 silly lifecycle aws-mobile-react-native-sample@0.1.0~preandroid: no script for preandroid, continuing
7 info lifecycle aws-mobile-react-native-sample@0.1.0~android: aws-mobile-react-native-sample@0.1.0
8 verbose lifecycle aws-mobile-react-native-sample@0.1.0~android: unsafe-perm in lifecycle true
11 silly lifecycle aws-mobile-react-native-sample@0.1.0~android: Args: [ '/d /s /c', 'react-native run-android' ]
12 silly lifecycle aws-mobile-react-native-sample@0.1.0~android: Returned: code: 1  signal: null
13 info lifecycle aws-mobile-react-native-sample@0.1.0~android: Failed to exec android script
14 verbose stack Error: aws-mobile-react-native-sample@0.1.0 android: `react-native run-android`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:194:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:194:7)
14 verbose stack     at maybeClose (internal/child_process.js:899:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid aws-mobile-react-native-sample@0.1.0

**Comment by smustaoglu** [comment]
Also need to define ANDROID_HOME to run correctly.

**Comment by powerful23** [comment]
Closing the issue.
