### ISSUE TITLE
documentation : packager server setting

### ISSUE THREAD

**Issue by smustaoglu** [awslabs/aws-mobile-react-native-starter#60]
afte apk installed on android phone, it cannot connect to packager server. there is a red screen. cannot connect localhost:8081. 

you should shake the phone to enter dev settings menu and entering ip address of your pc (packager server and port ) info.

**Comment by powerful23** [comment]
@smustaoglu can you make sure your did ```npm run android/ios``` and the packager is running?

**Comment by nidsharm** [comment]
Hi @smustaoglu ,
Try the following commands : 
1. sudo lsof -i tcp:8081 
2. kill -9 <pid> (this is the pid/s that you get from lsof)
3. adb reverse tcp:8081 tcp:8081 
4. REACT_NATIVE_PACKAGER_HOSTNAME=localhost yarn start

Please do let us know if you are still facing issues.

Thanks.
