### ISSUE TITLE
xcrun: error: unable to find utility "instruments"

### ISSUE THREAD

**Issue by gilbert** [awslabs/aws-mobile-react-native-starter#64]
Hi, I'm trying to set up a fresh project. Following the instructions up to `npm run ios`, I origionally got the error "Cannot find module 'xtend'", but following [this advice](https://github.com/awslabs/aws-mobile-react-native-starter/issues/61#issuecomment-366548134) I was able to fix by running `npm install` a second time.

However, now I am running into this error when I run `npm run ios` again:

```
Scanning 743 folders for symlinks in /Users/me/p/genuine/node_modules (10ms)
Found Xcode project awsmobilereactnativesample.xcodeproj
xcrun: error: unable to find utility "instruments", not a developer tool or in PATH

Command failed: xcrun instruments -s
xcrun: error: unable to find utility "instruments", not a developer tool or in PATH
```

Any ideas why this is happening?

**Comment by UnleashedMind** [comment]
I'd suggest you to go through the following 5 steps to make a clean slate and then try again. 
`lsof -n i4TCP:8081` to get the PID of the process that's using the port 8081
`kill -9 <above PID>`
`watchman watch-del-all`
`rm -rf node_modules/`
`npm cache clean --force`

Then you start over again 
`npm install`
`npm start --reset-cache`

Please let us know if it resolves this issue

**Comment by roubaka** [comment]
Having the same issue while just testing a basic AwesomeApp with React Native while running `react-native run-ios`. The process proposed by @UnleashedMind didn't work for me unfortunately. There seems to be a solution by [changing options on XCode](https://www.youtube.com/watch?v=Z_JH9_ZMj-M) but I still wonder if there is another way to fix that? Any idea is welcome!

**Comment by roubaka** [comment]
Thanks @kernel-sanders. The command line tool didn't worked for me but installing the whole Xcode App fixed it.
