### ISSUE TITLE
in npm install getting error

### ISSUE THREAD

**Issue by shojil** [awslabs/aws-mobile-react-native-starter#7]
We are getting error on npm install
on electron@1.7.5 postinstall
node install.js

after this there is long waiting

Got this error
Error: read ECONNRESET

**Comment by RTHRELKELD1980** [comment]
Can you provide more information on your environment setup and configuration? Are you trying to use this with an Electron application? This project is designed to be run with a standard React Native configuration.

**Comment by RTHRELKELD1980** [comment]
Closed

**Comment by shojil** [comment]
I was fixed when I remove all cache from command 
npm cache clean
then again try npm install and it work fine
