### ISSUE TITLE
facebook login integration

### ISSUE THREAD

**Issue by MatheusParanhos** [awslabs/aws-mobile-react-native-starter#8]
Hi everybody, does anyone knows how would I dig into facebook login with react-native and aws cognito? I've been doing this for a while and I feel that I'm stuck since there's no doc for this and all other repo there's ppl struggling as well. Thanks in advance

**Comment by nidsharm** [comment]
Hi @MatheusParanhos,

We have recently released [AWS Amplify](https://github.com/aws/aws-amplify) that includes integration with AWS Cognito and federated login with Facebook. You can follow the [Amplify Authentication Guide](https://github.com/aws/aws-amplify/blob/master/media/authentication_guide.md) to include Auth with Facebook and AWS Cognito in your React Native app.

Regards,
Nidhi

**Comment by flochaz** [comment]
FYI: From what it says here https://github.com/aws/aws-amplify/issues/87 it does not seems to be supported by the react-native lib ...
