### ISSUE TITLE
Malformed project configuration files. Resource creation failed for reactnativestarter-deployments-mobilehub-1381659999 bucket.

### ISSUE THREAD

**Issue by serkaniyigun** [awslabs/aws-mobile-react-native-starter#9]
Hi, trying import project but a different error from "An error occurred importing your project. Please try again later."

<img width="683" alt="screen shot 2017-10-10 at 09 39 19" src="https://user-images.githubusercontent.com/1617797/31372572-16f5a52c-ad9f-11e7-8d73-c092dd5561f7.png">

**Comment by rterysen** [comment]
I am experiencing the same issue.

**Comment by serkaniyigun** [comment]
thanks, you are right.
